version: '3.1'

services:

  lensesio-box:
    image: lensesio/box
    ports:
      - 3030:3030
      - 9092:9092
      - 8081:8081
    environment:
      - ADV_HOST=127.0.0.1
      - EULA=${EULA}

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    networks:
      - cluster
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  consul_data:
    driver: local
  mongodb:
    driver: local

networks:
  cluster:
    driver: overlay
  mongo_cluster:
    driver: overlay