version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - mongo_cluster
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - mongo_cluster

  consul:
    image: consul
    volumes:
      - consul_data:/bitnami/consul
    networks:
      - cluster
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'

  lensesio-box:
    image: lensesio/box
    ports:
      - 3030:3030
      - 9092:9092
      - 8081:8081
    environment:
      - ADV_HOST=127.0.0.1
      - EULA=${EULA}

volumes:
  consul_data:
    driver: local
  mongodb:
    driver: local

networks:
  cluster:
    driver: overlay
  mongo_cluster:
    driver: overlay